### ISSUE TITLE
Can´t find Chrome Web Store app

### ISSUE THREAD

**Issue by everterra** [gregolsky/chrome-app-launcher#67] opened 2017-05-19 11:51 UTC
I have Chrome Web Store app instaled and I can´t find it.

I seet it in the tab chrome://apps/

And in the Chrome Web Store can´t find the app to install...

**Comment by gregolsky** [comment] 2018-03-18 21:43
Yeah, webstore app is built-in. API doesn't return built-in apps, so I'm not sure how to tackle that.
We might hard-code some built-in apps based on Chromium sources and allow to opt-in in extension's options.

**Comment by gregolsky** [comment] 2018-07-09 19:32
Duplicate of #31

**Closed by gregolsky** 2018-07-09 19:32 UTC
Labels: duplicate, enhancement
